### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by MidnightWonderer** [cif/redux-fusion#3]
Hi I'm wondering why did you declare both  
`peerDependencies` and `dependencies`  
Can the dependencies be only inside `peerDependencies` and `devDependencies`?  
Can this library support react native which contains dependencies for react 16? anything breaking?

**Comment by cif** [comment]
In order to build a module on its own, node needs to know what its dependencies are (it won't install from peerDeps). When its consumed in a parent module, you can specify what peerDependencies may exist and affect that behavior. 

https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/

Also see this old issue thread https://github.com/cif/redux-fusion/issues/1 

Will keep this open in case you want to discuss or run into issues. The first issue opened was a learning process

**Comment by cif** [comment]
Also, I haven't used this with React Native just yet. If you want to try altering the peer dependency to follow major versions that would avoid warnings I am OK with that.

**Comment by cif** [comment]
Would moving dependencies into devDependencies do anything to help? In the way in which they are being used I suppose they really are "dev" dependencies
